import type { Chapter } from "./types";

// 3부 원고는 아직 웹으로 옮기지 못했다. 목차와 페이지는 인쇄본을 따르고,
// 본문이 준비되면 blocks 배열만 채우면 된다. (pending 플래그를 지우는 것도 잊지 말 것)
export const part3: Chapter[] = [
  {
    slug: "ch11",
    num: "11",
    part: 3,
    kicker: "CHAPTER 11 · SYNTHESIS",
    meta: "돌아와서",
    title: "8일을 관통하는 여덟 가지 발견",
    dek: "빅테크의 회의실과 스탠퍼드의 강의실이 공통으로 가리키던 방향.",
    keyMessage: "",
    context: "",
    page: 80,
    blocks: [],
    pending: true,
  },
  {
    slug: "ch12",
    num: "12",
    part: 3,
    kicker: "CHAPTER 12 · PLAYBOOK",
    meta: "돌아와서",
    title: "월요일 아침의 플레이북",
    dek: "이제 실행의 시간이다.",
    keyMessage: "",
    context: "",
    page: 85,
    blocks: [],
    pending: true,
  },
  {
    slug: "epilogue",
    num: "—",
    part: 3,
    kicker: "EPILOGUE",
    meta: "에필로그",
    title: "필요한 것은 이미 마음속에 있다",
    dek: "",
    keyMessage: "",
    context: "",
    page: 89,
    blocks: [],
    pending: true,
  },
  {
    slug: "appendix",
    num: "—",
    part: 3,
    kicker: "APPENDIX",
    meta: "부록",
    title: "방법론 미니 핸드북",
    dek: "",
    keyMessage: "",
    context: "",
    page: 91,
    blocks: [],
    pending: true,
  },
];
